### ISSUE TITLE
Missing platform-specific API docs

### ISSUE THREAD

**Issue by KelsamGames** [MonoGame/monogame.github.io#58]
### Link to Document

https://monogame.net/api/Microsoft.Xna.Framework.Input/

### Description

Both KeyboardInput and MessageBox appear to be missing from the API docs for Microsoft.Xna.Framework.Input. Perhaps there are other platform-specific features like this missing too?

Also, it seems the navigation only open sub-pages now so the only way to get to the parent page (i.e. https://monogame.net/api/Microsoft.Xna.Framework.Input/) is by navigating to one of those first and then clicking on the parent in the breadcrumb at the top of the page.

**Comment by JakeLegendXIII** [comment]
Hey @AristurtleDev wanted to draw some attention here as there is actually a lot of the API docs missing in the deployed site. It looks like sitemap.xml in all the recent [deployments (one example) ](https://github.com/MonoGame/monogame.github.io/blob/79b58f98d2f3bcb7e41573d3f5e2c615a2b4a73d/sitemap.xml) is missing almost a 1000 lines compared to my local build (2509 on mine 1593 in the deployment). Granted it seems to be missing since the big change as even your temp site [here](https://mgdocs.aristurtle.net/api/) is missing the same docs.  Things like SpriteBatch, GraphicsDeviceManager, and a ton of other docs are missing besides just the input stuff flagged here. I have like 50ish docs under the graphics namespace. There are only 20 on the website currently. Many of my fixes in the other PR are still going to 404s because of missing API reference pages.

Assuming it might be easier to test on your end with you temp site since you are currently able to do deployments. Locally it seems to build fine, but there may be some issue with the docfx stuff in the GitHub action? I can try an set something similar up, but figured you'd likely know better than me where to look!

**Comment by AristurtleDev** [comment]
Hey @JakeLegendXIII @KelsamGames  just now seeing this, looking into it.

**Comment by AristurtleDev** [comment]
This does seem to be an linux/ubuntu related issue. Changed the runner to use windows instead of ubuntu and it generated all docs fine (460 items).  Investigating further why this is happening on ubuntu since the windows runner is incredibly slow

<img width="316" alt="image" src="https://github.com/MonoGame/monogame.github.io/assets/103014489/046fa3ea-0d10-4ff7-8ffc-2ceb16b5eb3b">

**Comment by AristurtleDev** [comment]
@mrhelmut fixed in the #83 merge. This can be closed.

**Comment by KelsamGames** [comment]
@AristurtleDev KeyboardInput and MessageBox are still missing from Microsoft.Xna.Framework.Input.

**Comment by AristurtleDev** [comment]
Sorry @KelsamGames i got caught up with the issue that it was only generating half the documentation that I skipped over those parts.

The docfx generation only generates documentation from two projects
- MonoGame.Framework.DesktopGL.csproj
- MonoGame.Framework.Content.Pipeline.csproj

These were the original settings so I just used those when converting the site to 11ty.

It looks like the DesktopGL project specifically removes those two namespaces in the csproj

<img width="496" alt="image" src="https://github.com/MonoGame/monogame.github.io/assets/103014489/3b50c84d-b551-47dd-a4f8-24333a5a3ef4">

Since they are removed, they aren't part of the generation.  Going to have to add them in manually for docfx to include.

https://github.com/MonoGame/MonoGame/blob/6b8988fc19ec04015c7fa8279860932ba63b8ee4/MonoGame.Framework/MonoGame.Framework.DesktopGL.csproj#L42

**Comment by mrhelmut** [comment]
This is because the documentation is based on the DesktopGL target, which has no implementation for ```KeyboardInput``` and ```MessageBox``` (as well as ```Video``` and  ```VideoPlayer```).

Two possible solutions:
- base the documentation on WindowsDX instead (which would imply to build the website on Windows instead of Linux)
- or add empty implementations of those classes to DesktopGL throwing ```NotImplementedException``` (this one has my preference)

**Comment by AristurtleDev** [comment]
@mrhelmut I think we can add those two specific files to be included in the docfx settings along with the csprojs that we already have.

**Comment by mrhelmut** [comment]
That's cool, though I think that we should add empty implementations. I think it is a better user experience to let developers know that it's not implemented than having them missing.

It's a quick fix, I can work that out.

**Comment by AristurtleDev** [comment]
Ah yea that's a better solution 👍 

@KelsamGames I was just rereading the original issue, can you open a separate issue for this part 

> Also, it seems the navigation only open sub-pages now so the only way to get to the parent page (i.e. https://monogame.net/api/Microsoft.Xna.Framework.Input/) is by navigating to one of those first and then clicking on the parent in the breadcrumb at the top of the page.

I believe I know why this is happening and it's a bug in the way the html/css interacts to make the drop downs expand collapse. It's eating the click for the link when the expand/collapse triggers.

**Comment by KelsamGames** [comment]
Them being mentioned in any way (with that quick little blurb of what they're supposed to do) is my only goal. Back when I was making some mobile ports of past games, thumbing through the old docs had me stumble upon those 2 features that saved me GOBS of time with mobile keyboard handling and simple user alerts, so I'd really like them to be present in some way for others to notice the same way.

**Comment by KelsamGames** [comment]
> Ah yea that's a better solution 👍
> 
> @KelsamGames I was just rereading the original issue, can you open a separate issue for this part
> 
> > Also, it seems the navigation only open sub-pages now so the only way to get to the parent page (i.e. https://monogame.net/api/Microsoft.Xna.Framework.Input/) is by navigating to one of those first and then clicking on the parent in the breadcrumb at the top of the page.
> 
> I believe I know why this is happening and it's a bug in the way the html/css interacts to make the drop downs expand collapse. It's eating the click for the link when the expand/collapse triggers.

Sure thing.

**Comment by JakeLegendXIII** [comment]
> Sorry @KelsamGames i got caught up with the issue that it was only generating half the documentation that I skipped over those parts.
> 
> The docfx generation only generates documentation from two projects
> 
> * MonoGame.Framework.DesktopGL.csproj
> * MonoGame.Framework.Content.Pipeline.csproj

My bad @AristurtleDev ! I came out here to create an Issue for the missing the Api docs and noticed this one was already created. So I tagged you and wrote my giant wall of text about the other issue that should have probably been a separate issue had I stopped to check if these were in DesktopGL or not. 

Glad both issues are either fixed or have potential fixes in the works! Sorry for any confusion.

**Comment by mrhelmut** [comment]
I'm just waiting for https://github.com/MonoGame/MonoGame/pull/8142 to pass the build checks and I'll merge it. Then we can regenerate the documentation and have those types.

**Comment by mrhelmut** [comment]
Here we go #85
